name: sahm_project
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
    
  get: any
  google_fonts: ^2.1.0
  google_nav_bar: ^5.0.6
  


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/icons/

